### ISSUE TITLE
Move version tracking from parsing git files to basic version file

### ISSUE THREAD

**Issue by kylemhall** [Aspen-Discovery/aspen-discovery#1983]
Right now aspen determines it's own version by parsing git files. It appears the format of these files differs between git and/or OS versions. The first upgrade on a Debian server failed badly due to this. We should just have a version file in the root directory that contains the current version of Aspen installed.

**Comment by mdnoble73** [comment]
The issue with this looks to be the tagging of branches which changes the git file. The branch itself gets renamed from origin/24.08.00 to heads/24.08.00

**Comment by mdnoble73** [comment]
It looks like after the tag the git file has the internal id of the tag rather than the actual name

**Comment by mdnoble73** [comment]
Kirstien implemented a fix for this yesterday which uses the release notes to track versions
