### ISSUE TITLE
Digital links showing as physical items in Aspen

### ISSUE THREAD

**Issue by kylemhall** [Aspen-Discovery/aspen-discovery#2042]
Digital links entered in the 856 field are now showing as physical copies in Aspen.  The "location" of the item is whatever text we have entered in 856$y, Format is Online Content, Call number is 856$ Online, and status is Available Online. But none are the actual link.  For that the patron sees the "Available Online" button at the top of the page, or goes to the Links section - as usual.  This seems to be the case for all online content.

**Comment by mrenvoize** [comment]
@Chloe070196

**Comment by mdnoble73** [comment]
Is there an example of where this is wrong? That sounds like correct behavior if index856Links is turned on within Indexing Profiles.

**Comment by K-Alette** [comment]
@mdnoble73 they don't want them showing up in the copies section: 
![image](https://github.com/user-attachments/assets/4f4086dd-970d-4369-99c0-da6959c28963)

**Comment by K-Alette** [comment]
@mdnoble73 They don't want the 856 links showing in the copies section, just the links section: 
![Dig as phys item 219848](https://github.com/user-attachments/assets/8af1a2e4-ddb6-495d-87e1-4eca338295d7)

**Comment by mdnoble73** [comment]
That makes sense, thanks for clarifying

**Comment by Chloe070196** [comment]
Happy to add this bug to my to do list and see if I can sort out a patch for it if that's alright

**Comment by mdnoble73** [comment]
Kodi put a fix in for it yesterday

**Comment by mdnoble73** [comment]
I'm going to close this out since Kodi fixed it in 24.09
