### ISSUE TITLE
Add removing medium covers older than --interval cron task

### ISSUE THREAD

**Issue by lizrea** [Aspen-Discovery/aspen-discovery#2050]
Disk usage for medium covers can be extensive, and pruning them causes no harm - a cron job to find the png for covers/medium and remove them on a regular basis would be a very nice to have

**Comment by mdnoble73** [comment]
This already exists in cron BookCoverCleanup

**Comment by lizrea** [comment]
Cool, for anyone who's interested this is configured by going to /usr/local/aspen-discovery/sites/yoursite,production/config.cron.ini
